spring.application.name=ms-inscripciones

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

aws.region=us-east-1
aws.bucketName=ms-inscripciones

spring.security.user.name=admin
spring.security.user.password=1234

# Azure B2C
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/88fc8bd7-9e8f-454f-a388-461be6a93cc0/v2.0

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# RabbitMQ
spring.rabbitmq.host=100.31.112.56
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
